/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fyp.mips16.graphics;

import fyp.mips16.core.InstructionDecoder;
import fyp.mips16.core.MemoryMapper;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import fyp.mips16.core.ErrorManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import fyp.mips16.core.Error;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Akhil
 */
public class MIPS16Window extends javax.swing.JFrame {

    /**
     * Creates new form MIPS16Window
     */
    MemoryMapper mm;
    InstructionDecoder dec;
    int startaddress;
    boolean errorflag;
    File configfile,outfile;
    String directory,filename,statustext="";
    FileWriter  fout;
    public static ErrorManager em;
    Map <Integer,Integer> memorywrites;
    public MIPS16Window() {
        initComponents();
        directory="D:/";
        filename="testout";
        mm=new MemoryMapper(directory,filename);
        em=new ErrorManager();
        dec=new InstructionDecoder();
        outfile=new File(directory,filename+".asm");
        try {
            fout=new FileWriter(outfile);
        } catch (IOException ex) {
            Logger.getLogger(MIPS16Window.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //System.out.println(dec.DecodeLine("SBB r1,r2,r3"));
        //System.out.println(dec.DecodeLine("ADC r1,r2,r3"));
        //System.out.println(dec.DecodeLine("POP r1"));
        //System.out.println(dec.DecodeLine("Addi r5,r6,#0x1F"));
        startaddress=0;
        errorflag=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        editorarea = new javax.swing.JTextArea();
        assemblebut = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        writeaddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        writevalue = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        readaddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        readvalue = new javax.swing.JLabel();
        writebutton = new javax.swing.JButton();
        readbutton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        startaddrfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Openbutton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Exitbutton = new javax.swing.JButton();
        clearbuttton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MessageLabel = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MIPS 16 Assembler");

        editorarea.setColumns(20);
        editorarea.setRows(5);
        jScrollPane1.setViewportView(editorarea);

        assemblebut.setText("Assemble");
        assemblebut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assemblebutMouseClicked(evt);
            }
        });

        jLabel1.setText("Memory Editor");

        jLabel2.setText("Write Memory : Address");

        writeaddress.setText("0");

        jLabel3.setText("Value  ");

        writevalue.setText("0");

        jLabel4.setText("Read  Memory : Address");

        readaddress.setText("0");
        readaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readaddressActionPerformed(evt);
            }
        });

        jLabel5.setText("Value  ");

        readvalue.setText("0");
        readvalue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        writebutton.setText("Write");
        writebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                writebuttonMouseClicked(evt);
            }
        });
        writebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writebuttonActionPerformed(evt);
            }
        });

        readbutton.setText("Read");
        readbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readbuttonMouseClicked(evt);
            }
        });

        jLabel6.setText("Starting Address :");

        startaddrfield.setText("0");

        jLabel7.setText("Code Editor");

        jLabel9.setText("Output Directory :");

        jLabel11.setText("Load File :");

        jLabel12.setText("D:/testout.asm");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Openbutton.setText("Open");

        jLabel14.setText("(0 - 65535) ");

        jTextField2.setText("D:/");

        jTextField3.setText("testout");

        jLabel15.setText("Output Filename :");

        jLabel16.setText(".asm");

        Exitbutton.setText("Exit");
        Exitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitbuttonMouseClicked(evt);
            }
        });

        clearbuttton.setText("Clear");
        clearbuttton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearbutttonMouseClicked(evt);
            }
        });

        jLabel17.setText("Output");

        MessageLabel.setColumns(20);
        MessageLabel.setForeground(new java.awt.Color(255, 0, 0));
        MessageLabel.setLineWrap(true);
        MessageLabel.setRows(5);
        jScrollPane2.setViewportView(MessageLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(477, 477, 477)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(481, 481, 481)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(readaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(writeaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(writevalue, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(readvalue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(writebutton)
                            .addComponent(readbutton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(481, 481, 481)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(477, 477, 477)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(477, 477, 477)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(473, 473, 473)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startaddrfield, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(35, 35, 35))
                            .addComponent(jTextField2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addGap(47, 47, 47)
                                .addComponent(Openbutton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assemblebut, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearbuttton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Exitbutton, clearbuttton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(writeaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(writevalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(writebutton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(readaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(readvalue)
                    .addComponent(readbutton)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(startaddrfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(Openbutton))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assemblebut)
                    .addComponent(Exitbutton)
                    .addComponent(clearbuttton))
                .addGap(24, 24, 24))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Exitbutton, assemblebut, clearbuttton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void writebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_writebuttonActionPerformed

    private void readaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readaddressActionPerformed

    private void ExitbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitbuttonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitbuttonMouseClicked

    private void assemblebutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assemblebutMouseClicked
        // TODO add your handling code here:
        String lines[],addval[];
        statustext="";
        memorywrites=new HashMap<Integer,Integer>();
        int i,val=-2,ProgramCounter,a,b;
        String editorcontent;
        em.clear();
        startaddress=dec.NumberParser(startaddrfield.getText());
        
        errorflag=false;
        if(startaddress==-100000){
            startaddress =0;
            startaddrfield.setText(""+0);
        }
        ProgramCounter=startaddress;
        System.out.println("PC="+ProgramCounter);
        editorcontent=editorarea.getText();
        lines=editorcontent.split("\n");
        if(lines.length>0){
            Error x=new Error(0,-1,ErrorManager.MESSAGE_ASSEMBLING,outfile.getAbsolutePath());
            statustext=x.toString();
            MessageLabel.setText(statustext);
            
        }
        for(i=0;i<lines.length;i++){
            System.out.println(lines[i]);
            if(lines[i].contains("=")){
                addval=lines[i].split("=");
                //System.out.println("addval "+addval[0]+" "+addval[1] );
                //System.out.println("addval"+dec.NumberParser(addval[0])+" "+dec.NumberParser(addval[1]));
                a=dec.NumberParser(addval[0]);
                b=dec.NumberParser(addval[1]);
                if(addval.length == 2 && a!=ErrorManager.INVALID_NUMERAL&&b!=ErrorManager.INVALID_NUMERAL){
                    memorywrites.put(a%65536,a);
                    if(a%65536>= startaddress && a%65536 <= ProgramCounter)
                        em.add_message(1,i+1,ErrorManager.MEMORY_CODE_OVERLAP,""+ProgramCounter+":"+ProgramCounter+1);
                    if(a>65535)
                        em.add_message(1,i+1,ErrorManager.NUMERAL_OVERFLOW,addval[0]);
                    if(b>255)
                        em.add_message(1,i+1,ErrorManager.NUMERAL_OVERFLOW,addval[1]);
                    mm.writeMemory(a%65536, b%256);
                }else{
                    if(addval.length!=2)
                        em.add_message(2, i+1, ErrorManager.UNKNOWN_IDENTIFIER, lines[i]);
                    if(a==ErrorManager.INVALID_NUMERAL)
                        em.add_message(2, i+1, ErrorManager.INVALID_NUMERAL, addval[0]);
                    if(b==ErrorManager.INVALID_NUMERAL)
                        em.add_message(2, i+1, ErrorManager.INVALID_NUMERAL, addval[1]);
                    errorflag=true;
                }
            }
            else{
            val=dec.DecodeLine(lines[i],i+1);
            if(val<-1){
                errorflag=true;
                
            }
            else if(val==-1)
                continue;
            else{
                if(memorywrites.containsKey(ProgramCounter)||memorywrites.containsKey(ProgramCounter+1))
                    em.add_message(1,i+1,ErrorManager.MEMORY_CODE_OVERLAP,""+ProgramCounter+":"+ProgramCounter+1);
                mm.writeMemory(ProgramCounter, (val%256));
                mm.writeMemory(ProgramCounter+1, (val/256));
                ProgramCounter+=2;
                
            }
            }
        }
        if(errorflag==false){
            statustext+="\n";
            statustext+="0 Errors "+em.wrncnt+" Warnings;\n"; 
            statustext+=new Error(0,0,ErrorManager.MESSAGE_GENERATING_DUMP,mm.dumpFile.getAbsolutePath())+"\r\n";
            MessageLabel.setText(statustext);
            mm.dump(); 
            
        }
        try {
            statustext+="\n";
            //System.out.println(editorcontent);
            statustext+=new Error(0,0,ErrorManager.MESSAGE_SAVING_ASM,outfile.getAbsolutePath());
            statustext+="\r\n";
            MessageLabel.setText(statustext);
            if(errorflag==false)
               statustext+=new Error(0,0,ErrorManager.MESSAGE_SUCCESS,""); 
            else{
               statustext+=""+em.errcnt+" Errors "+em.wrncnt+" Warnings;\r\n";
               for(i=0;i<em.messagequeue.size();i++){
                   statustext+=em.messagequeue.get(i)+"\n";
               }
               statustext+=new Error(0,0,ErrorManager.MESSAGE_ASSEMBLING_FAILED,"");
               
            } 
            MessageLabel.setText(statustext);
            fout=new FileWriter(outfile);
            for(i=0;i<lines.length;i++){
            fout.write(lines[i]);
            fout.write("\r\n");
            }
            fout.close();
        } catch (IOException ex) {
            Logger.getLogger(MIPS16Window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_assemblebutMouseClicked

    private void writebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_writebuttonMouseClicked
        // TODO add your handling code here:
        String address=writeaddress.getText();
        int addr=dec.NumberParser(address);
        int val=dec.NumberParser(writevalue.getText());
        if(addr != -100000 && val!= -100000){
            mm.writeMemory(addr, val%256);
            writeaddress.setText(""+addr%65536);
        }else{
            writeaddress.setText("0");
            writevalue.setText("0");
        }
            
    }//GEN-LAST:event_writebuttonMouseClicked

    private void readbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readbuttonMouseClicked
        // TODO add your handling code here:
        int address=dec.NumberParser(readaddress.getText());
        if(address!=-100000){
            readvalue.setText(""+mm.readMemory(address));
            readaddress.setText(""+address%65536);
        }
    }//GEN-LAST:event_readbuttonMouseClicked

    private void clearbutttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearbutttonMouseClicked
        // TODO add your handling code here:
        editorarea.setText("");
    }//GEN-LAST:event_clearbutttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MIPS16Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MIPS16Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MIPS16Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MIPS16Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        
        MemoryMapper m= new MemoryMapper("D:/","testout.txt");
        m.dump();
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MIPS16Window().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exitbutton;
    private javax.swing.JTextArea MessageLabel;
    private javax.swing.JButton Openbutton;
    private javax.swing.JButton assemblebut;
    private javax.swing.JButton clearbuttton;
    private javax.swing.JTextArea editorarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField readaddress;
    private javax.swing.JButton readbutton;
    private javax.swing.JLabel readvalue;
    private javax.swing.JTextField startaddrfield;
    private javax.swing.JTextField writeaddress;
    private javax.swing.JButton writebutton;
    private javax.swing.JTextField writevalue;
    // End of variables declaration//GEN-END:variables
}
